#ifndef __SOLARNODE_VERSION_H__
#define __SOLARNODE_VERSION_H__

#define SOLARNODE_VERSION "0.2"
#define SOLARNODE_GIT_REV "%GITREV%"
#define SOLARNODE_BUILD_DATE "%BUILDDATE%"

#define UNIQUE_ID_ADDRESS 0x1FFFF7AC

#endif
